server:
  port:
    8083

spring.devtools.livereload.enabled:
  true

spring.thymeleaf.cache:
  true

spring.datasource.url:
  jdbc:mysql://localhost:8889/db_auction
spring.datasource.username:
  root
spring.datasource.password:
  root

spring:
  mvc:
    static-path-pattern: /static/**
  data:
    rest:
      base-path:
        /data-api
  jpa:
    show-sql:
      true
    hibernate:
      ddl-auto:
        update
    open-in-view:
      true
  main:
    allow-bean-definition-overriding=true:
